import type { Metadata } from "next";
import "./globals.css";
import { SiteHeader } from "@/components/layouts/site-header";
import { ThemeProvider } from "@/components/providers";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Scy Next",
	description: "Generated by scy",
	icons: {
		icon: "/icon.png",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="zh" suppressHydrationWarning>
			<body className={cn("min-h-screen bg-background antialiased")}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="relative flex min-h-screen flex-col">
						<SiteHeader />
						<main className="flex-1">{children}</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
